name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git clone https://github.com/AshleyBoehs/online-resume.git

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            -v ${{ https://github.com/AshleyBoehs/online-resume.git }}:/srv/jekyll -v ${{ https://github.com/AshleyBoehs/online-resume.git }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
